services:
  # Main API Service
  - type: web
    name: hustleplug-scheduling-api
    env: node
    plan: free
    buildCommand: |
      echo "=== BUILD DEBUG INFO ==="
      pwd
      ls -la
      echo "=== CHECKING FOR FILES ==="
      find . -name "package.json" -type f
      find . -name "server.js" -type f
      echo "=== INSTALLING DEPENDENCIES ==="
      if [ -f "package.json" ]; then
        npm install
      else
        echo "ERROR: package.json not found in current directory"
        exit 1
      fi
    startCommand: |
      echo "=== START DEBUG INFO ==="
      pwd
      ls -la
      echo "=== LOOKING FOR SERVER.JS ==="
      find . -name "server.js" -type f
      if [ -f "server.js" ]; then
        echo "Found server.js in current directory"
        node server.js
      else
        echo "server.js not found in current directory, searching..."
        SERVER_PATH=$(find . -name "server.js" -type f | head -1)
        if [ -n "$SERVER_PATH" ]; then
          echo "Found server.js at: $SERVER_PATH"
          cd $(dirname "$SERVER_PATH")
          node server.js
        else
          echo "ERROR: server.js not found anywhere"
          exit 1
        fi
      fi
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CRON_SECRET
        generateValue: true

  # Cron Job Service for Schedule Execution
  - type: cron
    name: hustleplug-schedule-executor
    env: node
    plan: free
    buildCommand: |
      echo "=== CRON BUILD DEBUG INFO ==="
      pwd
      ls -la
      find . -name "package.json" -type f
      if [ -f "package.json" ]; then
        npm install
      else
        echo "ERROR: package.json not found in current directory"
        exit 1
      fi
    schedule: "*/15 * * * *"
    startCommand: |
      echo "=== CRON START DEBUG INFO ==="
      pwd
      ls -la
      find . -name "cron-trigger.js" -type f
      if [ -f "package.json" ]; then
        npm run cron
      else
        echo "ERROR: package.json not found for npm run cron"
        exit 1
      fi
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        fromService:
          type: web
          name: hustleplug-scheduling-api
          property: host
      - key: CRON_SECRET
        fromService:
          type: web
          name: hustleplug-scheduling-api
          envVarKey: CRON_SECRET 