services:
  # Main API Service
  - type: web
    name: hustleplug-scheduling-api
    env: node
    plan: free
    buildCommand: ls -la && pwd && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CRON_SECRET
        generateValue: true

  # Cron Job Service for Schedule Execution
  - type: cron
    name: hustleplug-schedule-executor
    env: node
    plan: free
    buildCommand: ls -la && pwd && npm install
    schedule: "*/15 * * * *"
    startCommand: npm run cron
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        fromService:
          type: web
          name: hustleplug-scheduling-api
          property: host
      - key: CRON_SECRET
        fromService:
          type: web
          name: hustleplug-scheduling-api
          envVarKey: CRON_SECRET RET 
